DROP SCHEMA IF EXISTS DCRB;
CREATE SCHEMA DCRB;
USE DCRB;

-- CREATE THE TABLE THAT CONTAINS THE FILE SYSTEM
DROP TABLE IF EXISTS FILESYST;
CREATE TABLE FILESYST (
    FILE_ID INT AUTO_INCREMENT,
    FULL_PATH_NAME MEDIUMTEXT,
    FILE_NAME VARCHAR(255),
    FILE_TYPE CHAR(255),
    CONTENT LONGTEXT,
    PRIMARY KEY (FILE_ID)
);